server {
    listen 80;
    listen [::]:80;
    server_name frotasguest.duckdns.org;
    access_log /opt/frotasguest/logs/access.log;
    error_log /opt/frotasguest/logs/error.log;
    location ^~ /.well-known/acme-challenge/ { root /opt/frotasguest/acme; }
    location / { return 301 https://frotasguest.duckdns.org$request_uri; }
}
