import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
const credentials=JSON.parse(readFileSync(resolve(process.env.E2E_CREDENTIALS || '../.validation/e2e-credentials.json'),'utf8'));

test('200000 stays exact, workshop is typed and totals update before save',async({page},info)=>{
  await page.goto('/');
  await page.getByLabel('E-mail',{exact:true}).fill(credentials.email);
  await page.getByLabel('Senha',{exact:true}).fill(credentials.password);
  await page.getByRole('button',{name:'Entrar no FrotaGest'}).click();
  await expect(page.getByRole('heading',{name:'Visão geral',exact:true})).toBeVisible();
  await page.goto('/frota/novo');
  const n=String(Date.now()).slice(-4);
  const plate=`KM${info.project.name==='mobile'?'M':'D'}${n}`;
  await page.getByLabel('Placa *',{exact:true}).fill(plate);
  await page.getByLabel('Marca *',{exact:true}).fill('TESTE E2E Scania');
  await page.getByLabel('Modelo *',{exact:true}).fill('R450');
  const mileage=page.getByLabel('Quilometragem inicial');
  await mileage.fill('');
  await mileage.pressSequentially('200000');
  await expect(mileage).toHaveValue('200.000');
  await mileage.press('ArrowDown');
  await mileage.press('ArrowDown');
  await mileage.press('ArrowDown');
  await mileage.hover();
  await page.mouse.wheel(0,300);
  await expect(mileage).toHaveValue('200.000');
  await page.getByRole('button',{name:'Salvar registro'}).click();
  await expect(page).toHaveURL(/\/frota\/\d+$/);
  const id=page.url().split('/').at(-1)!;
  expect((await (await page.request.get(`/api/trucks/${id}`)).json()).mileage).toBe(200000);
  await page.reload();
  await expect(page.getByRole('heading',{name:'200.000 km'})).toBeVisible();
  await page.goto(`/manutencoes/nova?truck=${id}`);
  await expect(page.getByLabel('Quilometragem *',{exact:true})).toHaveValue('200.000');
  await page.getByLabel('Descrição *',{exact:true}).fill('Teste dos novos campos');
  await page.getByLabel('Descrição do serviço').fill('Troca de óleo');
  const labor = page.getByLabel('Mão de obra (R$)');
  await labor.fill('');
  await labor.pressSequentially('1');
  await expect(labor).toHaveValue('0,01');
  await labor.pressSequentially('23');
  await expect(labor).toHaveValue('1,23');
  await labor.press('Backspace');
  await expect(labor).toHaveValue('0,12');
  await labor.fill('');
  await labor.pressSequentially('50000');
  await expect(labor).toHaveValue('500,00');
  const workshop=`Oficina digitada ${plate}`;
  await page.getByLabel('Oficina',{exact:true}).fill(workshop);
  await page.getByRole('button',{name:'Peça',exact:true}).click();
  await page.getByLabel('Nome',{exact:true}).fill('Óleo');
  await page.getByLabel('Quantidade',{exact:true}).fill('20');
  await page.getByLabel('Valor unitário (R$)').fill('35');
  const other = page.getByLabel('Outros custos (R$)');
  await other.fill('');
  await other.pressSequentially('5000');
  await expect(other).toHaveValue('50,00');
  await expect(page.getByRole('region',{name:'Resumo de custos'})).toContainText('R$ 1.250,00');
  await page.getByLabel('Quantidade',{exact:true}).fill('10');
  await expect(page.getByRole('region',{name:'Resumo de custos'})).toContainText('R$ 900,00');
  await page.getByRole('button',{name:'Salvar registro'}).click();
  await expect(page).toHaveURL(/\/manutencoes\/\d+$/);
  await expect(page.getByText('R$ 900,00',{exact:true})).toBeVisible();
  await expect(page.getByText(workshop,{exact:true})).toBeVisible();
  await page.goto(`/frota/${id}`);
  page.once('dialog',dialog=>dialog.dismiss());
  await page.getByRole('button',{name:'Excluir caminhão',exact:true}).click();
  expect((await (await page.request.get(`/api/trucks/${id}`)).json()).active).toBe(true);
  page.once('dialog',dialog=>dialog.accept());
  await page.getByRole('button',{name:'Excluir caminhão',exact:true}).click();
  await expect(page).toHaveURL(/\/frota$/);
  await page.getByLabel('Buscar caminhão').fill(plate);
  await expect(page.getByText('Nenhum caminhão encontrado. Cadastre o primeiro veículo.')).toBeVisible();
  await page.getByLabel('Mostrar também caminhões excluídos/inativos').check();
  await expect(page.getByText(plate,{exact:true})).toBeVisible();
  await page.goto(`/frota/${id}?tab=historico`);
  await expect(page.getByRole('heading',{name:'Teste dos novos campos',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Excluir caminhão',exact:true})).toHaveCount(0);
});
