"""initial_schema"""
from alembic import op
import sqlalchemy as sa

revision = 'd0460406f62d'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=7), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('model_year', sa.Integer(), nullable=True),
    sa.Column('chassis', sa.String(length=40), nullable=True),
    sa.Column('renavam', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('mileage_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('driver', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DISPONIVEL','EM_MANUTENCAO','PARADO','INATIVO')"),
    sa.CheckConstraint('mileage >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chassis'),
    sa.UniqueConstraint('plate'),
    sa.UniqueConstraint('renavam')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'USUARIO')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workshops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('contact', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('interval_km', sa.Integer(), nullable=True),
    sa.Column('interval_months', sa.Integer(), nullable=True),
    sa.Column('baseline_km', sa.Integer(), nullable=False),
    sa.Column('baseline_date', sa.Date(), nullable=False),
    sa.Column('warning_km', sa.Integer(), nullable=False),
    sa.Column('warning_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('baseline_km >= 0 AND warning_km >= 0 AND warning_days >= 0'),
    sa.CheckConstraint('interval_km > 0 OR interval_months > 0'),
    sa.CheckConstraint('interval_km IS NULL OR interval_km > 0'),
    sa.CheckConstraint('interval_months IS NULL OR interval_months > 0'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_plans_truck_id'), 'maintenance_plans', ['truck_id'], unique=False)
    op.create_table('mileage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('mileage >= 0'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mileage_history_truck_id'), 'mileage_history', ['truck_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('parts_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ABERTA','AGENDADA','EM_ANDAMENTO','CONCLUIDA','CANCELADA')"),
    sa.CheckConstraint("type IN ('PREVENTIVA','CORRETIVA')"),
    sa.CheckConstraint('mileage >= 0'),
    sa.CheckConstraint('parts_cost >= 0 AND labor_cost >= 0 AND other_cost >= 0 AND total_cost = parts_cost + labor_cost + other_cost'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['maintenance_plans.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_date'), 'maintenance', ['date'], unique=False)
    op.create_index(op.f('ix_maintenance_plan_id'), 'maintenance', ['plan_id'], unique=False)
    op.create_index(op.f('ix_maintenance_truck_id'), 'maintenance', ['truck_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('storage_key', sa.String(length=80), nullable=False),
    sa.Column('mime', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_attachments_truck_id'), 'attachments', ['truck_id'], unique=False)
    op.create_table('maintenance_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0 AND unit_price >= 0 AND total >= 0'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_parts_maintenance_id'), 'maintenance_parts', ['maintenance_id'], unique=False)
    op.create_table('maintenance_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('value >= 0'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_services_maintenance_id'), 'maintenance_services', ['maintenance_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_services_maintenance_id'), table_name='maintenance_services')
    op.drop_table('maintenance_services')
    op.drop_index(op.f('ix_maintenance_parts_maintenance_id'), table_name='maintenance_parts')
    op.drop_table('maintenance_parts')
    op.drop_index(op.f('ix_attachments_truck_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_maintenance_truck_id'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_plan_id'), table_name='maintenance')
    op.drop_index(op.f('ix_maintenance_date'), table_name='maintenance')
    op.drop_table('maintenance')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_mileage_history_truck_id'), table_name='mileage_history')
    op.drop_table('mileage_history')
    op.drop_index(op.f('ix_maintenance_plans_truck_id'), table_name='maintenance_plans')
    op.drop_table('maintenance_plans')
    op.drop_table('audit_logs')
    op.drop_table('workshops')
    op.drop_table('users')
    op.drop_table('trucks')
    # ### end Alembic commands ###
